apm-server:
  host: localhost:8200

output:
  elasticsearch:
    hosts: elasticsearch:9200 

#output.elasticsearch:
 # index: "apm-%{[app.name]}-%{[beat.version]}-%{+yyyy.MM.dd}"
  
setup.kibana:
  host: "localhost:5601"
